name: testenv
channels:
- conda-forge
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - jupyter
  - jsonlines
  - keras
  - tensorflow
  - tqdm
  - seaborn
  - svg.path
  - rdp
  - scikit-learn
  - ipympl
